Jonas css opgaver
Sunese/CIT_Subproject3_Group01 pull request #16
Opened 2023-12-11 17:21 UTC by Hagel360

2023-12-11 17:22 UTC, Hagel360 commented
sune pls UwU 
:3 

^^

2023-12-12 14:37 UTC, Sunese commented on moviefrontend/src/components/Title/PopularActors.jsx
nameId skal bare nameID

2023-12-12 14:47 UTC, Sunese requested changes
se kommentarer ved de enkelte filer

2023-12-12 14:47 UTC, Sunese commented on moviefrontend/src/components/Title/PopularActors.jsx
> +          to={`/name/${item.nameId}`}
nameId skal være nameID

2023-12-12 14:47 UTC, Sunese commented on moviefrontend/src/components/Title/Directors.jsx
directors giver et undefined ID ved linket, plz fix

2023-12-12 14:47 UTC, Sunese commented on moviefrontend/src/components/Title/Writers.jsx
writers giver et undefined id ved linket plz fix

2023-12-12 14:47 UTC, Sunese commented on moviefrontend/src/components/KnownForTitles.jsx
imo skal title cards ved known for titles være endnu mindre

2023-12-13 09:14 UTC, Hagel360 commented on moviefrontend/src/components/KnownForTitles.jsx
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

2023-12-13 09:14 UTC, merged